### ISSUE TITLE
搭建问题

### ISSUE THREAD

**Issue by lfhuhu** [HanzLeader/hardware-mall#1]
你好，我在部署的时候遇到了一个问题，我在百度网盘中下载的图片应该放到哪个路径下呢
感谢！

**Comment by HanzLeader** [comment]
默认解压在D盘根目录，可在com.tyut.hardwaremall.common.Constants进行修改

**Comment by lfhuhu** [comment]
感谢你的指导！



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "HanzLeader"<notifications@github.com&gt;; 
发送时间: 2021年3月10日(星期三) 中午1:42
收件人: "HanzLeader/hardware-mall"<hardware-mall@noreply.github.com&gt;; 
抄送: "努力奔跑的小男孩"<759024328@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [HanzLeader/hardware-mall] 搭建问题 (#1)





 
默认解压在D盘根目录，可在com.tyut.hardwaremall.common.Constants进行修改

**Comment by alohaNetbios** [comment]
大神这个项目有没有说明文档之类的可以参考，跪求

**Comment by HanzLeader** [comment]
> 大神这个项目有没有说明文档之类的可以参考，跪求

暂时没有的

**Comment by Tugenn** [comment]
请问后台测试账号是什么
